alias c='clear'
alias rm='rm -i '
alias mv='mv -i '
alias cp='cp -i '
alias l='ls'
alias ls='/bin/ls -CF --color=auto'
alias la='/bin/ls -aldF --color=auto'
alias lt='/bin/ls -ltr --color=auto'
alias h='history'

alias cds='cd $ONLINE_HOME/src'
alias cdsql='cd $ONLINE_HOME/sql'
alias cdl='if [ -d  ~/log/`date +%Y%m%d` ]; then cd ~/log/`date +%Y%m%d`; else mkdir ~/log/`date +%Y%m%d`; cd ~/log/`date +%Y%m%d`; fi'
alias cdb='cd $ONLINE_HOME/bin'
alias cdi='cd $ONLINE_HOME/include'
alias cdlib='cd $ONLINE_HOME/lib'
alias cdsb='cd $ONLINE_HOME/sbin'
alias cde='cd $ONLINE_HOME/etc'
alias cgrep='find . -name "*.*c" | xargs grep -n'
alias hgrep='find . -name "*.h" | xargs grep -n'
alias rmlog='rm -f *.log*'
alias vi='vim'
alias sql='mysql ry -ubil -pbil -h127.0.0.1 --default-character-set=utf8mb4'
